config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'welcome#home'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'
  get '/user/:id', to: 'users#show', as: '/user'

  get '/login', to: 'sessions#new'
  post '/sessions', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/auth/:provider/callback', to: 'sessions#omniauth'

  resources :wines

  resources :wineries, only: [:index, :show, :new, :create] do
    resources :wines, only: [:index, :new, :create]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password

    validates :name, :email, presence: true
    validates :email, uniqueness: true

    has_many :wines, dependent: :delete_all
    has_many :wineries, through: :wines

    def self.create_from_omniauth(auth)
        User.find_or_create_by(uid: auth['uid'], provider: auth['provider']) do |u|
            u.name = auth['info']['first_name']
            u.email = auth['info']['email']
            u.password = SecureRandom.hex(16)
        end
    end
end

app/models/wine.rb
class Wine < ApplicationRecord
    belongs_to :user
    belongs_to :winery
    
    validates :name, :wine_type, :price, :year, presence: true
    validates :price, numericality: {greater_than: 0}

    def winery_attributes=(attr)
        if !attr[:name].blank?
            self.winery = Winery.find_or_create_by(name: attr[:name]) do |w|
                w.country = attr[:country]
                w.region = attr[:region]
                w.established = attr[:established]
            end
        end
    end

    def self.order_by_year
        self.order(year: :desc)
    end

    def self.order_by_price
        self.order(:price)
    end

    def self.order_by_name
        self.order(:name)
    end
end

app/models/winery.rb
class Winery < ApplicationRecord
    validates :name, :region, :country, presence: true
    validates :name, uniqueness: true

    has_many :wines
    has_many :users, through: :wines

    accepts_nested_attributes_for :wines
    
    def self.order_by_established
        self.order(:established)
    end

    def self.order_by_name
        self.order(:name)
    end

    def self.order_by_region
        self.order(:region)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    helper_method :current_user, :logged_in?, :enforce_login

    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
    end

    def logged_in?
        !!current_user
    end

    def enforce_login
        return redirect_to login_path unless logged_in?
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:message] = "Invalid credentials"
      redirect_to login_path
    end
  end

  def omniauth
    user = User.create_from_omniauth(auth)
    if user.valid?
        session[:user_id] = user.id
        flash[:message] = "Logged in via Omniauth"
        redirect_to root_path
    else
        flash[:message] = user.errors.full_messages.join("")
        redirect_to login_path
    end
  end

  def destroy
    reset_session
    redirect_to login_path
  end

  private
    def auth
      request.env['omniauth.auth']
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path
        else
            flash[:message] = @user.errors.full_messages.join("")
            render :new
        end
    end

    def show
        @user = User.find_by(id: params[:id])
    end

    private
        def user_params
            params.require(:user).permit(:name, :email, :password, :password_confirmation)
        end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :enforce_login
  
  def home
  end
end

app/controllers/wineries_controller.rb
class WineriesController < ApplicationController
    def index
        @wineries = Winery.all
    end

    def show
        @winery = Winery.find_by(id: params[:id])
    end

    def new
        @winery = Winery.new
        2.times {@winery.wines.build}
    end

    def create
        @winery = Winery.new(winery_params)
        if @winery.save
            redirect_to winery_path(@winery)
        else
            flash[:message] = @winery.errors.full_messages.join("")
            render :new
        end
    end

    private
        def winery_params
            params.require(:winery).permit(:name, :state, :country, :region, :established, wines_attributes: [:name, :wine_type, :year, :price, :opened, :notes])
        end
end

app/controllers/wines_controller.rb
class WinesController < ApplicationController
    def index
        if params[:winery_id] && @winery = Winery.find_by_id(params[:winery_id])
            @wines = @winery.wines.order_by_year
        else
            @wines = Wine.order_by_year
        end
    end

    def show 
        @wine = Wine.find_by(id: params[:id])
    end

    def new
        if params[:winery_id] && @winery = Winery.find_by_id(params[:winery_id])
            @wine = @winery.wines.build
        else
            @wine = Wine.new
            @wine.build_winery
        end
    end

    def create
        @wine = current_user.wines.build(wine_params)
        if @wine.save
            redirect_to wine_path(@wine)
        else
            flash[:message] = @wine.errors.full_messages.join("")
            render :new
        end
    end

    def edit
        @wine = Wine.find_by(id: params[:id])
    end

    def updated
        wine = Wine.find_by(id: params[:id])
        wine.update(wine_params)
        redirect_to wine_path(wine)
    end

    def destroy
        wine = Wine.find_by(id: params[:id])
        wine.destroy
        redirect_to user_path(current_user)
    end

    private
        def wine_params
            params.require(:wine).permit(:name, :wine_type, :year, :price, :opened, :notes, :winery_id, winery_attributes: [:name, :state, :country, :region, :established])
        end
end

app/helpers/application_helper.rb
module ApplicationHelper
    def nav_bar
        if logged_in?
            "Hi, #{current_user.name} | #{link_to "Wine List", wines_path} | #{link_to "Winery List", wineries_path} | #{link_to "Logout", logout_path}"
        end
    end
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/wine_helper.rb
module WineHelper
    def header_display(wine)
        if wine
            tag.h1("All #{wine.name} Wines")
        else
            tag.h2("All Wines")
        end
    end

    def display_winery_fields(winery, f)
        if winery
            f.hidden_field :winery_id #will send wine_id in via params without user seeing anything
        else
            render partial: 'winery_select', locals: {f: f}
        end
    end
end

app/helpers/winery_helper.rb
module WineryHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMioVino</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <br>
    <%= nav_bar %><br>
    Hi, <%= link_to current_user.name, user_path(current_user) %> | <%= link_to "Wine List", wines_path %> | <%= link_to "Winery List", wineries_path %> | <%= link_to "Logout", logout_path %>
    <% if flash[:message] %>
      <br><br>
      <div class="fields_with_errors"><%= flash[:message] %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/new.html.erb
<h1>Mio Vino Signup</h1>
<%= form_with(model: @user, url: '/signup', local: true) do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %><br><br>
    <%= f.label :email %>
    <%= f.email_field :email %><br><br>
    <%= f.label :password %>
    <%= f.password_field :password %><br><br>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %><br><br>
    <%= f.submit %>
<% end %>

app/views/users/show.html.erb
<h1><%= @user.name %></h1>

<h3>Your Wines</h3>
<ul>
    <% @user.wines.each do |w| %>
        <li><%= link_to w.name, wine_path(w) %></li>
    <% end %>
</ul>
<br><br>
<%= link_to "Add New Wine", new_wine_path %>

app/views/welcome/home.html.erb
<h1>Welcome to MioVino!</h1>

<%= button_to "Logout", logout_path, method: :delete %>

app/views/wineries/index.html.erb
<h1>Wineries</h1>
<ul>
    <% @wineries.each do |winery| %>
        <li><%= link_to winery.name, winery_path(winery) %></li>
    <% end %>
</ul>
<br><br>
<%= button_to "Add Winery", new_winery_path, method: :get %>

app/views/wineries/new.html.erb
<h1>New Winery</h1>

<%= form_for(@winery) do |f| %>
    <%= f.label :name, "Winery Name:" %>
    <%= f.text_field :name %><br>
    <%= f.label :state %>: 
    <%= f.text_field :state %><br>
    <%= f.label :country %>: 
    <%= f.text_field :country %><br>
    <%= f.label :region %>: 
    <%= f.text_field :region %><br>
    <%= f.label :established %>: 
    <%= f.number_field :established, min: 1800 %><br>
    <hr><br>
    <%= f.fields_for :wines do |w| %>
        <%= w.label :name, "Wine Name:" %>
        <%= w.text_field :name %><br>
        <%= w.label :wine_type, "Wine Type: " %>
        <%= w.select :wine_type, ["Cabernet Sauvignon", "Cabernet Franc", "Malbec","Syrah", "Zinfandel", "Pinot Noir", "Chardonnay", "Sauvignon Blanc", "Pinot Gris", "Riesling"], prompt: "Select Type" %><br>
        <%= w.label :year %>: 
        <%= w.number_field :year, min: 1800 %><br>
        <%= w.label :price %>: $
        <%= w.number_field :price, min: 0 %><br>
        <%= w.label :opened %>: 
        <%= w.check_box :opened %><br>
        <%= w.label :notes %>: 
        <%= w.text_area :notes %><br><br>
    <% end %>
    <%= f.submit %>
<% end %>

app/views/wineries/show.html.erb
<h1><%= @winery.name %></h1>
<h3>Established <%= @winery.established %></h3>
<h4>Location: <%= @winery.state %> (<%= @winery.country %>)</h4>
<h4>Region: <%= @winery.region %></h4>
<br><br>
<h2>Wines</h2>
<ul>
    <% @winery.wines.each do |w| %>
        <li><%= link_to "#{w.name} (#{w.year})", wine_path(w) %> Owned By: <%= link_to w.user.name, user_path(w.user) %></li><br>
    <% end %>
</ul>

<%= link_to "Add #{@winery.name} Wine", new_winery_wine_path(@winery) %>

app/views/wines/_form.html.erb
<% if @wine.errors.any? %>
    <div id="error_explanation">
    <h2> <%= pluralize(@wine.errors.count, "error") %> prohibited entry from being saved: </h2>
    <ul>
        <% @wine.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
    </ul>
    </div>
<% end %>

<%= form_for [@winery, @wine] do |f| %>
    <%= f.label :name, "Wine Name:"%>
    <%= f.text_field :name %><br>
    <%= f.label :wine_type, "Wine Type: " %>
    <%= f.select :wine_type, ["Cabernet Sauvignon", "Cabernet Franc", "Malbec", "Red Blend", "Syrah", "Zinfandel", "Pinot Noir", "Chardonnay", "Sauvignon Blanc", "Pinot Gris", "Riesling"], prompt: "Select Type" %><br>
    <%= f.label :year %>: 
    <%= f.number_field :year, min: 1800 %><br>
    <%= f.label :price %>: $
    <%= f.number_field :price, min: 0 %><br>
    <%= f.label :opened %>: 
    <%= f.check_box :opened %><br>
    <%= f.label :notes %>: 
    <%= f.text_area :notes %><br>
    <%= display_winery_fields(@winery, f) %>
    <%= f.submit %>
<% end %>

app/views/wines/_winery_select.html.erb
<br><hr><br>Select Existing or Create New Winery<br><br>
    <%= f.label :name, "Winery Name:" %>
    <%= f.collection_select :winery_id, Winery.all, :id, :name, prompt: "Select Winery" %>
    <%= f.fields_for :winery do |w| %>
        <%= w.label :country %>:
        <%= w.text_field :country %><br>
        <%= w.label :region %>:
        <%= w.text_field :region %><br>
        <%= w.label :established %>:
        <%= w.number_field :established, min: 1800 %><br><br><br>
    <% end %>

app/views/wines/edit.html.erb
<h1>Edit Wine</h1>

<%= render 'form' %>

app/views/wines/index.html.erb
<h1>Wines</h1>
<ul>
<% @wines.each do |w| %>
    <li><%= link_to w.name, wine_path(w) %>: <%= w.winery.name %> (<%= w.year %>)</li>
<% end %>
</ul>
<br>
<%= button_to "Add New Wine", new_wine_path, method: :get %>

app/views/wines/new.html.erb
<h1>New Wine</h1>

<%= render 'form' %>

app/views/wines/show.html.erb
<h1><%= @wine.name %></h1>
<ul>
    Winery: <%= link_to @wine.winery.name, winery_path(@wine.winery) %><br>
    Type: <%= @wine.wine_type %><br>
    Year: <%= @wine.year %><br>
    Price: $<%= @wine.price %><br>
    Opened? <%= @wine.opened ? "Yes" : "No" %><br>
    Notes: <%= @wine.notes %><br>
    <br>
    Added: <%= @wine.created_at %><br>
    Updated: <%= @wine.updated_at %>
</ul>
<br>
<%= link_to "Edit #{@wine.name}", edit_wine_path(@wine) %> 